src/KnowledgeCompetitionWebApp/Models/Competition.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace KnowledgeCompetitionWebApp.Models
{
    public class Competition
    {
        public int Id { get; set; }
        public string CompetitionCode { get; set; }
        public DateTime CreatedDate { get; set; }
        public int UserId { get; set; }
        public int CategoryId { get; set; }

        [ForeignKey("UserId")]
        public virtual User User { get; set; }
        
        public List<Question> Questions { get; set; }
        public List<Result> Results { get; set; }
    }
}

src/KnowledgeCompetitionWebApp/Models/CompetitionDetail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KnowledgeCompetitionWebApp.Models
{
    public class CompetitionDetail
    {
        public User User { get; set; }
        public Competition Competition { get; set; }
        public List<Question> Questions { get; set; }
        public List<Result> Results { get; set; }
        public List<CorrectAnswer> CorrectAnswers { get; set; }
        public string CategoryName { get; set; }
    }
}

src/KnowledgeCompetitionWebApp/Models/Result.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KnowledgeCompetitionWebApp.Models
{
    public class Result
    {
        public int Id { get; set; }
        public string SelectedOption { get; set; }
        public int CompetitionId { get; set; }
        public Competition Competition { get; set; }
        public List<Question> Questions { get; set; }
    }
}

src/KnowledgeCompetitionWebApp/Controllers/EditController.cs
using KnowledgeCompetitionWebApp.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KnowledgeCompetitionWebApp.Controllers
{
    public class EditController : Controller
    {
        public Context dbContext { get; set; }
        public EditController()
        {
            dbContext = new Context();
        }
        public JsonResult GetUser(int id)
        {

            var user = dbContext.Users.Where(u => u.Id == id).FirstOrDefault();

            return Json(new {
                id = user.Id,
                name = user.Name,
                surname = user.Surname,
                email = user.Email
            });
        }

        public JsonResult User(string name, string surname, string email, int id)
       
 {
            try
            {
                if (dbContext.Users.Where(u => u.Id != id).Any(u => u.Email.Trim() == email.Trim()))
                    return Json(new { status = 2 });
                var user = dbContext.Users.Where(u => u.Id == id).FirstOrDefault();
                user.Name = name;
                user.Surname = surname;
                user.Email = email;
                dbContext.SaveChanges();

                return Json(new
                {
                    id = user.Id,
                    name = user.Name,
                    surname = user.Surname,
                    email = user.Email,
                    status = 1
                });
            }
            catch (Exception ex)
            {
                return Json(new {
                    status = 0
                });
            }
        }

        public JsonResult GetCategory(int id)
        {

            var category = dbContext.Categories.Where(c => c.Id == id).FirstOrDefault();

            return Json(new
            {
                id = category.Id,
                name = category.Name,
                isActive = category.IsActive
            });
        }

        public JsonResult Category(int id, string categoryName, bool isActive)

        {
            try
            {
                if (dbContext.Categories.Where(q => q.Id != id).Any(c => c.Name.Trim() == categoryName.Trim()))
                    return Json(new { status = 2 });
                var categoryEntity = dbContext.Categories.Where(c => c.Id == id).FirstOrDefault();
                categoryEntity.Name = categoryName;
                categoryEntity.IsActive = isActive;

                dbContext.SaveChanges();

                return Json(new
                {
                    status = 1
                });
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    status = 0
                });
            }
        }

        public JsonResult GetQuestion(int id)
        {

            var question = dbContext.Questions.Where(q => q.Id == id).FirstOrDefault();

            return Json(new
            {
                id = question.Id,
                question = question.QuestionTxt,
                optionA = question.OptionA,
                optionB = question.OptionB,
                optionC = question.OptionC,
                optionD = question.OptionD,
                correctOption = dbContext.CorrectAnswers.Where(a => a.QuestionId == id).FirstOrDefault().CorrectOption,
                category = question.CategoryId,
                categoryName = dbContext.Categories.Where(c => c.Id == question.CategoryId).Select(c => c.Name).FirstOrDefault(),
                level = question.Level
            });
        }

        public JsonResult Question(string question, string optionA, string optionB, string optionC, string optionD, string correct, int categoryId, int level, int id)
        {
            try
            {
                var questionEntity = dbContext.Questions.Where(q => q.Id == id).FirstOrDefault();
                questionEntity.QuestionTxt = question;
                questionEntity.OptionA = optionA;
                questionEntity.OptionB = optionB;
                questionEntity.OptionC = optionC;
                questionEntity.OptionD = optionD;
                questionEntity.CategoryId = categoryId;
                questionEntity.Level = level;

                var correctAnswer = dbContext.CorrectAnswers.Where(a => a.QuestionId == id).FirstOrDefault();
                correctAnswer.CorrectOption = correct;

                dbContext.SaveChanges();

                return Json(
                    new
                    {
                        status = 1
                    }
                );

            }
            catch (Exception)
            {

                return Json(
                    new
                    {
                        status = 0
                    }
                );
            }
        }

        public JsonResult Password(string OldPassword, string NewPassword)
        {
            try
            {
                //if (Session["userId"] == null || Session["userType"] == null || Session["userName"] == null || Session["surName"] == null || Session["userEmail"] == null)
                //return Json(new { status = 0 });
                int userID = Convert.ToInt32(Session["userId"]);
                var user = dbContext.Users.Where(u => u.Id == userID && u.Password == OldPassword.Trim()).FirstOrDefault();
                if(user == null)
                    return Json(new { status = 2 });

                user.Password = NewPassword;
                dbContext.SaveChanges();
                return Json(new { status = 1 });

            }
            catch (Exception ex)
            {
                return Json(new { status = 0 });
            }

        }
    }
}

src/KnowledgeCompetitionWebApp/Controllers/SaveController.cs
using KnowledgeCompetitionWebApp.Helpers;
using KnowledgeCompetitionWebApp.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KnowledgeCompetitionWebApp.Controllers
{
    public class SaveController : Controller
    {
        public Context dbContext { get; set; }
        public SaveController()
        {
            dbContext = new Context();
        }


        public JsonResult User(string name, string surname, string email, string password = "" , int userType = -1)
        {
            try
            {
                if (dbContext.Users.Any(p => p.Email.Trim() == email.Trim()))
                    return Json(new { status = 2 });
                if (userType == -1)
                    throw new Exception();

                Guid guid = Guid.NewGuid();
                password = Convert.ToBase64String(guid.ToByteArray()).Substring(0,6);

                string mailBody = GetMailBody(name, password);

                if (!MailOperations.SendRegistrationMail(email, mailBody))
                    throw new Exception();

                User user = new User
                {
                    Name = name,
                    Surname = surname,
                    Password = password,
                    Email = email,
                    UserType = userType
                };

                dbContext.Users.Add(user);
                dbContext.SaveChangesAsync();
                return Json(new { status = 1 });

            }
            catch (Exception ex)
            {
                return Json(new { status = 0 });
            }
        }

        public JsonResult Category(string categoryName, string color, bool isActive)
        {
            try
            {
                if (dbContext.Categories.Any(c => c.Name.ToLower().Trim() == categoryName.ToLower().Trim()))
                    return Json(new { status = 2 });

                if (string.IsNullOrEmpty(categoryName))
                    throw new Exception();
                Category category = new Category
                {
                    Name = categoryName,
                    Color = color,
                    IsActive = isActive
                };

                dbContext.Categories.Add(category);
                dbContext.SaveChanges();
                return Json(new { status = 1 });

            }
            catch (Exception ex)
            {

                return Json(
                    new
                    {
                        status = 0
                    }
                );
            }

        }

        public JsonResult Question(string question, string optionA, string optionB, string optionC, string optionD, string correct, int categoryId, int level)
        {
            try
            {
                if (string.IsNullOrEmpty(question) || string.IsNullOrEmpty(optionA) || string.IsNullOrEmpty(optionB) ||
                    string.IsNullOrEmpty(optionC) || string.IsNullOrEmpty(optionD) || string.IsNullOrEmpty(correct) || categoryId <= 0)
                    throw new Exception();
                Question questionEntity = new Question
                {
                    QuestionTxt = question,
                    OptionA = optionA,
                    OptionB = optionB,
                    OptionC = optionC,
                    OptionD = optionD,
                    CategoryId = categoryId,
                    Level = level
                };

                dbContext.Questions.Add(questionEntity);

                var questionId = questionEntity.Id;

                CorrectAnswer correctEntity = new CorrectAnswer
                {
                    CorrectOption = correct,
                    QuestionId = questionId
                };

                dbContext.CorrectAnswers.Add(correctEntity);

                dbContext.SaveChanges();
                return Json(
                    new
                    {
                        status = 1
                    }
                );

            }
            catch (Exception)
            {

                return Json(
                    new
                    {
                        status = 0
                    }
                );
            }
        }

        public JsonResult Competition(int id = -1)
        {
            try
            {
                List<Question> CompetitionQuestions = new List<Question>();
                Random randomQuestionIndex = new Random();
                if (id == -1)
                    throw new Exception();
                if (Session["userType"] == null || Convert.ToInt32(Session["userType"]) != 2)
                    return Json(new { status = 2 });
                var questions = dbContext.Questions.Where(q => q.CategoryId == id).ToList();

                for (int i = 1; i < 11; i++)
                {
                    int questionCount = questions.Count(q => q.Level == i);
                    int index = randomQuestionIndex.Next(0, questionCount);

                    var questionsInLevel = questions.Where(q => q.Level == i).ToList();

                    CompetitionQuestions.Add(questionsInLevel[index]);
                }

                Guid guid = Guid.NewGuid();
                string competitionCode = Convert.ToBase64String(guid.ToByteArray());
                competitionCode = competitionCode.Replace("=", "")
                                                 .Replace("+", "")
                                                 .Replace("-", "")
                                                 .Replace("/", "");
                int userId = Convert.ToInt32(Session["userId"]);
                Competition competition = new Competition
                {
                    CompetitionCode = competitionCode,
                    CreatedDate = DateTime.Now,
                    Questions = CompetitionQuestions,
                    UserId = userId,
                    CategoryId = id
                };

                dbContext.Competitions.Add(competition);
                dbContext.SaveChanges();
                return Json(
                    new
                    {
                        status = 1,
                        code = competitionCode
                    }
                );
            }
            catch (Exception)
            {

                return Json(
                    new
                    {
                        status = 0
                    }
                );

            }

        }

        public JsonResult Result(string selectedOption, int competitionId = 0)
        {
            try
            {
                if (Session["userType"] == null || Convert.ToInt32(Session["userType"]) != 2)
                    return Json(new { status = 2 });
                if (competitionId == 0 || string.IsNullOrEmpty(selectedOption))
                    throw new Exception();

                var result = new Result
                {
                    CompetitionId = competitionId,
                    SelectedOption = selectedOption
                };

                dbContext.Results.Add(result);
                dbContext.SaveChanges();

                return Json(new { status = 1 });
            }
            catch (Exception)
            {
                dbContext.Results.RemoveRange(dbContext.Results.Where(r => r.CompetitionId == competitionId));
                dbContext.SaveChanges();
                return Json(new { status = 0 });
            }
            
        }
        private string GetMailBody(string name, string password)
        {
            return RenderPartialViewToString("_EmailLayout", new RegisterEmail { Name = name, Password = password });
        }
        protected string RenderPartialViewToString(string viewName, object model)
        {
            if (string.IsNullOrEmpty(viewName))
                viewName = ControllerContext.RouteData.GetRequiredString("action");

            ViewData.Model = model;


            using (StringWriter sw = new StringWriter())
            {
                ViewEngineResult viewResult = ViewEngines.Engines.FindPartialView(ControllerContext, viewName);
                ViewContext viewContext = new ViewContext(ControllerContext, viewResult.View, ViewData, TempData, sw);
                viewResult.View.Render(viewContext, sw);

                return sw.GetStringBuilder().ToString();
            }
        }
    }
}

src/KnowledgeCompetitionWebApp/Views/Student/AvailableCompetition.cshtml
@{
    ViewBag.Title = "AvailableCompetition";
    Layout = "~/Views/Shared/_StudentLayout.cshtml";
}


@foreach (var category in Model)
{
    <a data-id="@category.Id" class="category-selection">
        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
            <div class="card">
                <div class="header @category.Color">
                    <h2>
                        @category.Name.ToUpper()<small>Yarışma başlatmak için tıklayınız...</small>
                    </h2>
                </div>
            </div>
        </div>
    </a>
}

<div class="row clearfix js-sweetalert">
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
        <p></p>
        <button id="failCompErr" class="btn btn-primary waves-effect" data-type="basic" style="display:none;"></button>
    </div>
</div>

@section styles
{
    <link href="~/plugins/sweetalert/sweetalert.css" rel="stylesheet" />
    <style>
        .category-selection {
            cursor: pointer;
        }
    </style>
}

@section scripts{
    <script src="~/plugins/sweetalert/sweetalert.min.js"></script>
    <script src="~/Scripts/pages/ui/dialogs.js"></script>
    <script>
        $(document).ready(function () {
            $(".category-selection").click(function (e) {
                e.preventDefault();
                let id = $(this).data('id');
                console.log(id);
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("Competition", "Save")',
                    data: {
                        id: id
                    },
                    dataType :'json',
                    success: function (data) {
                        if (data.status === 1) {
                            window.location.href = "@Url.Action("Competition", "Student")?competition=" + data.code;
                        }
                        else if (data.status === 2) {
                            window.location.href = "@Url.Action("Index", "Login")";
                        }
                        else {
                            $("#failCompErr").click();
                            //alert("Yarışma başlatılamadı!");
                        }
                    }
                });
            });
        });
    </script>
}

src/KnowledgeCompetitionWebApp/Views/Student/Competition.cshtml
@model KnowledgeCompetitionWebApp.Models.Competition
@{
    Layout = "~/Views/Shared/_StudentLayout.cshtml";
}

@for (int i = 0; i < Model.Questions.Count(); i++)
{
    var id = "q" + (i + 1).ToString();
    <div class="row clearfix question" id="@id">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">

                <div class="body">
                    <strong>SORU: </strong>
                    @Model.Questions.ElementAt(i).QuestionTxt
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <div class="card option" data-opt="a">
                <div class="body">
                    <strong>A)&nbsp;</strong>
                    @Model.Questions.ElementAt(i).OptionA
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <div class="card option" data-opt="b">

                <div class="body">
                    <strong>B)&nbsp;</strong>
                    @Model.Questions.ElementAt(i).OptionB
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <div class="card option" data-opt="c">

                <div class="body">
                    <strong>C)&nbsp;</strong>
                    @Model.Questions.ElementAt(i).OptionC
                </div>
            </div>
        </div>

        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <div class="card option" data-opt="d">

                <div class="body">
                    <strong>D)&nbsp;</strong>
                    @Model.Questions.ElementAt(i).OptionD
                </div>
            </div>
        </div>


    </div>
}

@section styles{
    <style>
        .card {
            cursor: pointer !important;
        }
    </style>
}

@section scripts{
    <script>
            var currentQuestion = 1;
            var selectedOption = "";
            var competitionId = @Model.Id;
            $(document).ready(function () {
                $(".question").hide();
                ShowNextQuestion();
                $(".option").hover(function () {
                    $(this).addClass("bg-light-blue");
                });
                $(".option").mouseout(function () {
                    $(this).removeClass("bg-light-blue");
                });
                $(".card").click(function (e) {
                    selectedOption = $(this).data("opt");
                    $("#q" + currentQuestion).fadeOut();

                    $.ajax({
                        type: "POST",
                        url: "@Url.Action("Result", "Save")",
                        data: {
                            selectedOption: selectedOption,
                            competitionId: competitionId
                        },
                        dataType : "json",
                        success: function (data) {
                            if (data.status === 1) {
                                currentQuestion++;
                                setTimeout(function () {
                                    $("#q" + currentQuestion).fadeIn();
                                    if (currentQuestion > 10) {
                                        alert("Yarışma Bitti");
                                        window.location.href = "@Url.Action("Results", "Student")?ResultId=" + competitionId;
                                    }
                                }, 500);
                            }
                            else if (data.status === 2) {
                                window.location.href = "@Url.Action("Index", "Login")";
                            }
                            else {
                                alert("Sistemde teknik bir arıza oluştu.Özür dileriz...");
                                window.location.href = '@Url.Action("AvailableCompetition", "Student")';
                            }
                        }
                    });
                });
            });

            function ShowNextQuestion() {
                console.log(currentQuestion);
                $("#q" + currentQuestion).show();
            }

    </script>
}

src/KnowledgeCompetitionWebApp/Views/Student/CompetitionDetail.cshtml
@model KnowledgeCompetitionWebApp.Models.CompetitionDetail
@{
    Layout = "~/Views/Shared/_StudentLayout.cshtml";
}


<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    YARIŞMA KODU : @Model.Competition.CompetitionCode
                </h2>
                <h5>
                    Kategori Adı : @Model.CategoryName
                </h5>
                <small>Tarih - Saat: @Model.Competition.CreatedDate.ToString("dd/MM/yyyy - HH:mm:ss")</small>
            </div>
            <div class="body table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>SORU</th>
                            <th>SEVİYE</th>
                            <th>DOĞRU CEVAP</th>
                            <th>VERİLEN CEVAP</th>
                            <th>DURUM</th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (int i = 0; i < Model.Questions.Count; i++)
                        {
                            <tr>
                                <th scope="row">@(i + 1)</th>
                                <td>@Model.Questions.ElementAt(i).QuestionTxt</td>
                                <td>@Model.Questions.ElementAt(i).Level</td>
                                <td>
                                    <strong>
                                        @Model.CorrectAnswers.ElementAt(i).CorrectOption.ToUpper()
                                    </strong>
                                </td>
                                <td>
                                    @if (i < Model.Results.Count)
                                    {

                                        <strong>
                                            @Model.Results.ElementAt(i).SelectedOption.ToUpper()
                                        </strong>
                                    }
                                    else
                                    {
                                        <strong>
                                            BOŞ
                                        </strong>
                                    }
                                </td>
                                <td>
                                    @if (i < Model.Results.Count)
                                    {
                                        if (Model.CorrectAnswers.ElementAt(i).CorrectOption == Model.Results.ElementAt(i).SelectedOption)
                                        {
                                            <i class="material-icons">done</i>
                                        }
                                        else
                                        {
                                            <i class="material-icons">clear</i>
                                        }
                                    }
                                    else
                                    {
                                        <i class="material-icons">clear</i>
                                    }
                                </td>
                            </tr>
                        }


                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>

src/KnowledgeCompetitionWebApp/Views/Student/Results.cshtml
@model IEnumerable<KnowledgeCompetitionWebApp.Models.ResultsToDisplay>
@{
    Layout = "~/Views/Shared/_StudentLayout.cshtml";
}

@if (Model.Count() < 1)
{
    <div class="alert alert-info">
        <strong>Bilgilendirme: </strong> Öğrenciye ait herhangi bir yarışma geçmişi bulunamadı.
    </div>
}
else
{


    <div class="row clearfix">
        @foreach (var result in Model)
        {
            <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12 result" data-competition="">
                <div class="card">
                    <div class="body">
                        <div class="list-group">
                            <a href="javascript:void(0);" class="list-group-item active">
                                <h4 class="list-group-item-heading"><strong>Kategori: </strong>@result.CategoryName.ToUpper()</h4>

                            </a>
                            <a href="javascript:void(0);" class="list-group-item">
                                <h4 class="list-group-item-heading"><strong>Tarih-Saat: </strong>@result.CompetitionDate.ToString("dd/MM/yyyy - HH:mm:ss")</h4>
                            </a>
                            <a href="javascript:void(0);" class="list-group-item">
                                <h4 class="list-group-item-heading"><strong>Sorulan Soru Adeti: </strong>@result.QuestionsCount</h4>
                            </a>
                            <a href="javascript:void(0);" class="list-group-item">
                                <h4 class="list-group-item-heading"><strong>Cevaplanan Soru Adeti: </strong>@result.AnsweredCount</h4>
                            </a>
                            <a href="@Url.Action("Results", "Student", new { ResultId = result.CompetitionId})" class="btn btn-block btn-lg btn-primary waves-effect"><i class="material-icons">web</i> <span>Görüntüle</span></a>
                        </div>
                    </div>
                </div>
            </div>
        }

    </div>
}

src/KnowledgeCompetitionWebApp/Views/Student/UserProfile.cshtml
@{
    ViewBag.Title = "Profile";
    Layout = "~/Views/Shared/_StudentLayout.cshtml";
}


@Html.Partial("~/Views/Shared/ChangePassword.cshtml")

@section scripts{
    <script>
        $(document).ready(function () {
            $(".alert").hide();
            $('form').submit(function (event) {
                event.preventDefault();
                if ($('.pass').val().trim() === '' || $('.pass').val().length < 6 || $('.pass').val().length > 20) {
                    return;
                }
                else if ($('#NewPassword').val() !== $('#NewPasswordCnfrm').val()) {
                    console.log($('#NewPassword').val());
                    console.log($('#NewPasswordCnfrm').val());
                    $('#NotMatched').fadeIn();
                    setTimeout(function () {
                        $('#NotMatched').fadeOut();
                    }, 2000);
                }
                else if ($('#NewPassword').val() === $('#OldPassword').val()) {
                    $('#NotChange').fadeIn();
                    setTimeout(function () {
                        $('#NotChange').fadeOut();
                    }, 2000);
                }
                else {
                    $.ajax({
                        type: 'POST',
                        url: '@Url.Action("Password", "Edit")',
                        data: {
                            OldPassword: $('#OldPassword').val().trim(),
                            NewPassword: $('#NewPassword').val().trim(),
                        },
                        datatype: "json",
                        success: function (data) {
                            if (data.status === 0) {
                                $('#PassErr').fadeIn();
                                setTimeout(function () {
                                    $('#PassErr').fadeOut();
                                }, 2000);
                            }
                            else if (data.status === 1) {
                                $('.alert-success').fadeIn();
                                setTimeout(function () {
                                    $('.alert-success').fadeOut();
                                    location.href = "@Url.Action("SignOut", "Login")";
                                }, 2000);
                            }
                            else if (data.status === 2) {
                                $('#NotInDb').fadeIn();
                                setTimeout(function () {
                                    $('#NotInDb').fadeOut();
                                }, 2000);
                            }
                        }
                    });
                    $('#form_advanced_validation').trigger("reset");
                }
            });
        });
    </script>

}