src/KnowledgeCompetitionWebApp/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KnowledgeCompetitionWebApp.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public string Color { get; set; }
    }
}

src/KnowledgeCompetitionWebApp/Models/CompetitionDetail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KnowledgeCompetitionWebApp.Models
{
    public class CompetitionDetail
    {
        public User User { get; set; }
        public Competition Competition { get; set; }
        public List<Question> Questions { get; set; }
        public List<Result> Results { get; set; }
        public List<CorrectAnswer> CorrectAnswers { get; set; }
        public string CategoryName { get; set; }
    }
}

src/KnowledgeCompetitionWebApp/Models/Result.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KnowledgeCompetitionWebApp.Models
{
    public class Result
    {
        public int Id { get; set; }
        public string SelectedOption { get; set; }
        public int CompetitionId { get; set; }
        public Competition Competition { get; set; }
        public List<Question> Questions { get; set; }
    }
}

src/KnowledgeCompetitionWebApp/Controllers/DeleteController.cs
using KnowledgeCompetitionWebApp.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KnowledgeCompetitionWebApp.Controllers
{
    public class DeleteController : Controller
    {
        public Context dbContext { get; set; }
        public DeleteController()
        {
            dbContext = new Context();
        }


        public JsonResult User(int id)
        {
            try
            {
                var user = dbContext.Users.Where(s => s.Id == id).FirstOrDefault();
                if(user == null)
                    throw new Exception();

                dbContext.Users.Remove(user);
                dbContext.SaveChanges();
                return Json(new { status = 1 });
                
            }
            catch (Exception ex)
            {
                return Json(new { status = 0 });
            }
        }

        public JsonResult Category(int id)
        {
            try
            {
                var category = dbContext.Categories.Where(s => s.Id == id).FirstOrDefault();
                if (category == null)
                    throw new Exception();

                dbContext.Categories.Remove(category);
                dbContext.SaveChanges();
                return Json(new { status = 1 });

            }
            catch (Exception ex)
            {
                return Json(new { status = 0 });
            }
        }

        public JsonResult Question(int id)
        {
            try
            {
                var question = dbContext.Questions.Where(q => q.Id == id).FirstOrDefault();
                if (question == null)
                    throw new Exception();
                dbContext.Questions.Remove(question);
                dbContext.SaveChanges();
                return Json(new { status = 1 });
            }
            catch (Exception)
            {

                return Json(new { status = 0 });
            }
        }
    }
}

src/KnowledgeCompetitionWebApp/Controllers/EditController.cs
using KnowledgeCompetitionWebApp.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KnowledgeCompetitionWebApp.Controllers
{
    public class EditController : Controller
    {
        public Context dbContext { get; set; }
        public EditController()
        {
            dbContext = new Context();
        }
        public JsonResult GetUser(int id)
        {

            var user = dbContext.Users.Where(u => u.Id == id).FirstOrDefault();

            return Json(new {
                id = user.Id,
                name = user.Name,
                surname = user.Surname,
                email = user.Email
            });
        }

        public JsonResult User(string name, string surname, string email, int id)
       
 {
            try
            {
                if (dbContext.Users.Where(u => u.Id != id).Any(u => u.Email.Trim() == email.Trim()))
                    return Json(new { status = 2 });
                var user = dbContext.Users.Where(u => u.Id == id).FirstOrDefault();
                user.Name = name;
                user.Surname = surname;
                user.Email = email;
                dbContext.SaveChanges();

                return Json(new
                {
                    id = user.Id,
                    name = user.Name,
                    surname = user.Surname,
                    email = user.Email,
                    status = 1
                });
            }
            catch (Exception ex)
            {
                return Json(new {
                    status = 0
                });
            }
        }

        public JsonResult GetCategory(int id)
        {

            var category = dbContext.Categories.Where(c => c.Id == id).FirstOrDefault();

            return Json(new
            {
                id = category.Id,
                name = category.Name,
                isActive = category.IsActive
            });
        }

        public JsonResult Category(int id, string categoryName, bool isActive)

        {
            try
            {
                if (dbContext.Categories.Where(q => q.Id != id).Any(c => c.Name.Trim() == categoryName.Trim()))
                    return Json(new { status = 2 });
                var categoryEntity = dbContext.Categories.Where(c => c.Id == id).FirstOrDefault();
                categoryEntity.Name = categoryName;
                categoryEntity.IsActive = isActive;

                dbContext.SaveChanges();

                return Json(new
                {
                    status = 1
                });
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    status = 0
                });
            }
        }

        public JsonResult GetQuestion(int id)
        {

            var question = dbContext.Questions.Where(q => q.Id == id).FirstOrDefault();

            return Json(new
            {
                id = question.Id,
                question = question.QuestionTxt,
                optionA = question.OptionA,
                optionB = question.OptionB,
                optionC = question.OptionC,
                optionD = question.OptionD,
                correctOption = dbContext.CorrectAnswers.Where(a => a.QuestionId == id).FirstOrDefault().CorrectOption,
                category = question.CategoryId,
                categoryName = dbContext.Categories.Where(c => c.Id == question.CategoryId).Select(c => c.Name).FirstOrDefault(),
                level = question.Level
            });
        }

        public JsonResult Question(string question, string optionA, string optionB, string optionC, string optionD, string correct, int categoryId, int level, int id)
        {
            try
            {
                var questionEntity = dbContext.Questions.Where(q => q.Id == id).FirstOrDefault();
                questionEntity.QuestionTxt = question;
                questionEntity.OptionA = optionA;
                questionEntity.OptionB = optionB;
                questionEntity.OptionC = optionC;
                questionEntity.OptionD = optionD;
                questionEntity.CategoryId = categoryId;
                questionEntity.Level = level;

                var correctAnswer = dbContext.CorrectAnswers.Where(a => a.QuestionId == id).FirstOrDefault();
                correctAnswer.CorrectOption = correct;

                dbContext.SaveChanges();

                return Json(
                    new
                    {
                        status = 1
                    }
                );

            }
            catch (Exception)
            {

                return Json(
                    new
                    {
                        status = 0
                    }
                );
            }
        }

        public JsonResult Password(string OldPassword, string NewPassword)
        {
            try
            {
                //if (Session["userId"] == null || Session["userType"] == null || Session["userName"] == null || Session["surName"] == null || Session["userEmail"] == null)
                //return Json(new { status = 0 });
                int userID = Convert.ToInt32(Session["userId"]);
                var user = dbContext.Users.Where(u => u.Id == userID && u.Password == OldPassword.Trim()).FirstOrDefault();
                if(user == null)
                    return Json(new { status = 2 });

                user.Password = NewPassword;
                dbContext.SaveChanges();
                return Json(new { status = 1 });

            }
            catch (Exception ex)
            {
                return Json(new { status = 0 });
            }

        }
    }
}

src/KnowledgeCompetitionWebApp/Controllers/SaveController.cs
using KnowledgeCompetitionWebApp.Helpers;
using KnowledgeCompetitionWebApp.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KnowledgeCompetitionWebApp.Controllers
{
    public class SaveController : Controller
    {
        public Context dbContext { get; set; }
        public SaveController()
        {
            dbContext = new Context();
        }


        public JsonResult User(string name, string surname, string email, string password = "" , int userType = -1)
        {
            try
            {
                if (dbContext.Users.Any(p => p.Email.Trim() == email.Trim()))
                    return Json(new { status = 2 });
                if (userType == -1)
                    throw new Exception();

                Guid guid = Guid.NewGuid();
                password = Convert.ToBase64String(guid.ToByteArray()).Substring(0,6);

                string mailBody = GetMailBody(name, password);

                if (!MailOperations.SendRegistrationMail(email, mailBody))
                    throw new Exception();

                User user = new User
                {
                    Name = name,
                    Surname = surname,
                    Password = password,
                    Email = email,
                    UserType = userType
                };

                dbContext.Users.Add(user);
                dbContext.SaveChangesAsync();
                return Json(new { status = 1 });

            }
            catch (Exception ex)
            {
                return Json(new { status = 0 });
            }
        }

        public JsonResult Category(string categoryName, string color, bool isActive)
        {
            try
            {
                if (dbContext.Categories.Any(c => c.Name.ToLower().Trim() == categoryName.ToLower().Trim()))
                    return Json(new { status = 2 });

                if (string.IsNullOrEmpty(categoryName))
                    throw new Exception();
                Category category = new Category
                {
                    Name = categoryName,
                    Color = color,
                    IsActive = isActive
                };

                dbContext.Categories.Add(category);
                dbContext.SaveChanges();
                return Json(new { status = 1 });

            }
            catch (Exception ex)
            {

                return Json(
                    new
                    {
                        status = 0
                    }
                );
            }

        }

        public JsonResult Question(string question, string optionA, string optionB, string optionC, string optionD, string correct, int categoryId, int level)
        {
            try
            {
                if (string.IsNullOrEmpty(question) || string.IsNullOrEmpty(optionA) || string.IsNullOrEmpty(optionB) ||
                    string.IsNullOrEmpty(optionC) || string.IsNullOrEmpty(optionD) || string.IsNullOrEmpty(correct) || categoryId <= 0)
                    throw new Exception();
                Question questionEntity = new Question
                {
                    QuestionTxt = question,
                    OptionA = optionA,
                    OptionB = optionB,
                    OptionC = optionC,
                    OptionD = optionD,
                    CategoryId = categoryId,
                    Level = level
                };

                dbContext.Questions.Add(questionEntity);

                var questionId = questionEntity.Id;

                CorrectAnswer correctEntity = new CorrectAnswer
                {
                    CorrectOption = correct,
                    QuestionId = questionId
                };

                dbContext.CorrectAnswers.Add(correctEntity);

                dbContext.SaveChanges();
                return Json(
                    new
                    {
                        status = 1
                    }
                );

            }
            catch (Exception)
            {

                return Json(
                    new
                    {
                        status = 0
                    }
                );
            }
        }

        public JsonResult Competition(int id = -1)
        {
            try
            {
                List<Question> CompetitionQuestions = new List<Question>();
                Random randomQuestionIndex = new Random();
                if (id == -1)
                    throw new Exception();
                if (Session["userType"] == null || Convert.ToInt32(Session["userType"]) != 2)
                    return Json(new { status = 2 });
                var questions = dbContext.Questions.Where(q => q.CategoryId == id).ToList();

                for (int i = 1; i < 11; i++)
                {
                    int questionCount = questions.Count(q => q.Level == i);
                    int index = randomQuestionIndex.Next(0, questionCount);

                    var questionsInLevel = questions.Where(q => q.Level == i).ToList();

                    CompetitionQuestions.Add(questionsInLevel[index]);
                }

                Guid guid = Guid.NewGuid();
                string competitionCode = Convert.ToBase64String(guid.ToByteArray());
                competitionCode = competitionCode.Replace("=", "")
                                                 .Replace("+", "")
                                                 .Replace("-", "")
                                                 .Replace("/", "");
                int userId = Convert.ToInt32(Session["userId"]);
                Competition competition = new Competition
                {
                    CompetitionCode = competitionCode,
                    CreatedDate = DateTime.Now,
                    Questions = CompetitionQuestions,
                    UserId = userId,
                    CategoryId = id
                };

                dbContext.Competitions.Add(competition);
                dbContext.SaveChanges();
                return Json(
                    new
                    {
                        status = 1,
                        code = competitionCode
                    }
                );
            }
            catch (Exception)
            {

                return Json(
                    new
                    {
                        status = 0
                    }
                );

            }

        }

        public JsonResult Result(string selectedOption, int competitionId = 0)
        {
            try
            {
                if (Session["userType"] == null || Convert.ToInt32(Session["userType"]) != 2)
                    return Json(new { status = 2 });
                if (competitionId == 0 || string.IsNullOrEmpty(selectedOption))
                    throw new Exception();

                var result = new Result
                {
                    CompetitionId = competitionId,
                    SelectedOption = selectedOption
                };

                dbContext.Results.Add(result);
                dbContext.SaveChanges();

                return Json(new { status = 1 });
            }
            catch (Exception)
            {
                dbContext.Results.RemoveRange(dbContext.Results.Where(r => r.CompetitionId == competitionId));
                dbContext.SaveChanges();
                return Json(new { status = 0 });
            }
            
        }
        private string GetMailBody(string name, string password)
        {
            return RenderPartialViewToString("_EmailLayout", new RegisterEmail { Name = name, Password = password });
        }
        protected string RenderPartialViewToString(string viewName, object model)
        {
            if (string.IsNullOrEmpty(viewName))
                viewName = ControllerContext.RouteData.GetRequiredString("action");

            ViewData.Model = model;


            using (StringWriter sw = new StringWriter())
            {
                ViewEngineResult viewResult = ViewEngines.Engines.FindPartialView(ControllerContext, viewName);
                ViewContext viewContext = new ViewContext(ControllerContext, viewResult.View, ViewData, TempData, sw);
                viewResult.View.Render(viewContext, sw);

                return sw.GetStringBuilder().ToString();
            }
        }
    }
}

src/KnowledgeCompetitionWebApp/Views/Admin/Admin.cshtml
@model IEnumerable<KnowledgeCompetitionWebApp.Models.User>
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="row clearfix m-b-10">
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
        <a href="@Url.Action("NewAdmin", "Admin")" class="btn bg-green waves-effect">
            <i class="material-icons">save</i>
            <span>YÖNETİCİ EKLE</span>
        </a>
    </div>
</div>

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    YÖNETİCİLER
                </h2>
            </div>
            <div class="body">
                @if (Model == null || !Model.Any(t => t.UserType == 0) || (Model.Count() == 1))
                {
                    <div class="alert alert-danger">
                        <strong>Üzgünüz!</strong> Sistemde gösterilecek yönetici bulunmamaktadır.
                    </div>
                }
                else
                {
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                            <thead>
                                <tr>
                                    <th>Adı</th>
                                    <th>Soyad</th>
                                    <th>Email</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th>Adı</th>
                                    <th>Soyad</th>
                                    <th>Email</th>
                                    <th></th>
                                </tr>
                            </tfoot>
                            <tbody>
                                @foreach (var admin in Model)
                                {
                                    if (Convert.ToInt32(Session["userId"]) != admin.Id)
                                    {
                                        <tr id="user_@admin.Id">
                                            <th id="col_name_@admin.Id">@admin.Name</th>
                                            <th id="col_surname_@admin.Id">@admin.Surname</th>
                                            <th id="col_name_@admin.Id">@admin.Email</th>
                                            <th>
                                                <button type="button" class="btn bg-orange waves-effect" id="edit_@admin.Id" onclick="Edit(@admin.Id)" data-toggle="modal">
                                                    <i class="material-icons">mode_edit</i>
                                                    <span>Düzenle</span>
                                                </button>
                                                <button type="button" class="btn bg-red waves-effect" id="delete_@admin.Id" onclick="Delete(@admin.Id)">
                                                    <i class="material-icons">report_problem</i>
                                                    <span>Sil</span>
                                                </button>
                                            </th>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>

                    <div class="alert alert-success m-t-10 info-alert" id="delete_success">
                        <strong>Başarılı!</strong> Silme işlemi gerçekleşti.
                    </div>
                    <div class="alert alert-danger m-t-10 info-alert" id="delete_err">
                        <strong>Hata!</strong> Silme işlemi bir sepebten ötürü başarısız oldu.
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="UpdateUserModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <form id="form_advanced_validation" method="POST">
                <div class="modal-header">
                    <h4 class="modal-title" id="UpdateUserModalLabel">Öğrenci Güncelleme Ekranı</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group form-float">
                        <div class="form-line">
                            <input id="name" type="text" class="form-control" name="name" required="" aria-required="true">
                        </div>
                    </div>
                    <div class="form-group form-float">
                        <div class="form-line">
                            <input id="surname" type="text" class="form-control" name="surname" required="" aria-required="true">
                        </div>
                    </div>
                    <div class="form-group form-float">
                        <div class="form-line">
                            <input id="email" type="email" class="form-control" name="email" required="" aria-required="true" aria-invalid="true">
                        </div>
                        <label id="email-error" class="error" for="email" style="display: none;"></label>
                    </div>
                    <input type="hidden" id="id" name="id" />
                    <div class="alert alert-success m-t-10 info-alert" id="update_success">
                        <strong>Başarılı!</strong> Güncelleme işlemi gerçekleşti.
                    </div>
                    <div class="alert alert-danger m-t-10 info-alert" id="update_err">
                        <strong>Hata!</strong> Güncelleme işlemi bir sepebten ötürü başarısız oldu.
                    </div>
                    <div class="alert alert-warning m-t-10 info-alert" id="update_warning">
                        <strong>Uyarı!</strong> Bu e-maile sahip bir kullanıcı zaten var.
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-danger waves-effect">Kaydet</button>
                    <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">Kapat</button>
                </div>
            </form>
        </div>
    </div>
</div>


@section scripts{
    <script>
            $(document).ready(function () {
                $('.info-alert').hide();
                $("#form_advanced_validation").submit(function (e) {
                    e.preventDefault();
                    if ($('input[name="name"]').val().trim() === '' || $('input[name="surname"]').val().trim() === '' || $('input[name="email"]').val().trim() === '') {
                        return;
                    }
                    else if (!isValidEmailAddress($('input[name="email"]').val().trim())) {
                        return;
                    }
                    else {
                        $.ajax({
                            type: "POST",
                            url: '@Url.Action("User", "Edit")',
                            data: {
                                name: $('input[name="name"]').val().trim(),
                                surname: $('input[name="surname"]').val().trim(),
                                email: $('input[name="email"]').val().trim(),
                                id: $('#id').val().trim()
                            },
                            dataType: "json",
                            success: function (data) {
                                if (data.status === 0) {
                                    $("#update_err").fadeIn();
                                    setTimeout(function () {
                                        $("#update_err").fadeOut();
                                        $("#UpdateUserModal").modal("hide");
                                    }, 2000);
                                }
                                else if (data.status === 1) {
                                    $("#col_name_" + data.id).html(data.name);
                                    $("#col_surname_" + data.id).html(data.surname);
                                    $("#col_email_" + data.id).html(data.email);
                                    $("#update_success").fadeIn();
                                    setTimeout(function () {
                                        $("#update_success").fadeOut();
                                        $("#UpdateUserModal").modal("hide");
                                    }, 2000);

                                }
                                else {
                                    $("#update_warning").fadeIn();
                                    setTimeout(function () {
                                        $("#update_warning").fadeOut();
                                        $("#UpdateUserModal").modal("hide");
                                    }, 2000);
                                }
                            }
                        });
                    }
                });
            });
            function Edit(id) {
                if (id === null)
                    return;
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("GetUser", "Edit")',
                    data: { id: id },
                    dataType: "json",
                    success: function (data) {
                        $("#name").val(data.name);
                        $("#surname").val(data.surname);
                        $("#email").val(data.email);
                        $("#id").val(data.id);
                        $("#UpdateUserModal").modal("show");
                    }
                });
            }

            function Delete(id) {
                if (confirm("Öğrenciyi silmek istediğinize emin misiniz?")) {
                    $.ajax({
                        type: 'POST',
                        url: '@Url.Action("User", "Delete")',
                        data: { id : id },
                        datatype: "json",
                        success: function (data) {
                            if (data.status === 1) {
                                $("#user_" + id).fadeOut();
                                $("#delete_success").fadeIn();
                                setTimeout(function () {
                                    $("#delete_success").fadeOut();
                                }, 2000);
                            } else {
                                $("#delete_err").fadeIn();
                                setTimeout(function () {
                                    $("#delete_err").fadeOut();
                                }, 2000);
                            }
                        }
                    });
                }
            }
    </script>
}

src/KnowledgeCompetitionWebApp/Views/Admin/UserProfile.cshtml
@{
    ViewBag.Title = "Profile";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@Html.Partial("~/Views/Shared/ChangePassword.cshtml")

@section scripts{
    <script>
        $(document).ready(function () {
            $(".alert").hide();
            $('form').submit(function (event) {
                event.preventDefault();
                if ($('.pass').val().trim() === '' || $('.pass').val().length < 6 || $('.pass').val().length > 20) {
                    return;
                }
                else if ($('#NewPassword').val() !== $('#NewPasswordCnfrm').val()) {
                    console.log($('#NewPassword').val());
                    console.log($('#NewPasswordCnfrm').val());
                    $('#NotMatched').fadeIn();
                    setTimeout(function () {
                        $('#NotMatched').fadeOut();
                    }, 2000);
                }
                else if ($('#NewPassword').val() === $('#OldPassword').val()) {
                    $('#NotChange').fadeIn();
                    setTimeout(function () {
                        $('#NotChange').fadeOut();
                    }, 2000);
                }
                else {
                    $.ajax({
                        type: 'POST',
                        url: '@Url.Action("Password", "Edit")',
                        data: {
                            OldPassword: $('#OldPassword').val().trim(),
                            NewPassword: $('#NewPassword').val().trim(),
                        },
                        datatype: "json",
                        success: function (data) {
                            if (data.status === 0) {
                                $('#PassErr').fadeIn();
                                setTimeout(function () {
                                    $('#PassErr').fadeOut();
                                }, 2000);
                            }
                            else if (data.status === 1) {
                                $('.alert-success').fadeIn();
                                setTimeout(function () {
                                    $('.alert-success').fadeOut();
                                    location.href = "@Url.Action("SignOut", "Login")";
                                }, 2000);
                            }
                            else if (data.status === 2) {
                                $('#NotInDb').fadeIn();
                                setTimeout(function () {
                                    $('#NotInDb').fadeOut();
                                }, 2000);
                            }
                        }
                    });
                    $('#form_advanced_validation').trigger("reset");
                }
            });
        });
    </script>

}